### ISSUE TITLE
infrequently fails with a 400 status code 

### ISSUE THREAD

**Issue by danverde** [byuitechops/course-make-backup#1]
This is the error. It doesn't seem to be related to any particular course. It is infrequent, but still occurs often enough it should be looked into.

```
Status Code 400 | PUT | https://byui.instructure.com/api/v1/courses/11342/blueprint_templates/default/update_associations | [object Object] stack: Error: Status Code 400 | PUT
```

**Comment by zachintosh** [comment]
@danverde I haven't had this issue. Have you seen it at all lately?

**Comment by zachintosh** [comment]
Hasn't occurred in a week or so.
